{% set xorg_name = "libxcvt" %}
{% set xorg_category = "lib" %}
{% set name = "xorg-" ~ xorg_name %}
{% set version = "0.1.3" %}
{% set sha256 = "a929998a8767de7dfa36d6da4751cdbeef34ed630714f2f4a767b351f2442e01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.xz
  url: https://www.x.org/releases/individual/{{ xorg_category }}/{{ xorg_name }}-{{ version }}.tar.xz
  sha256: {{ sha256 }}

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower) }}

requirements:
  build:
    - pkg-config                   # [unix]
    - m2-pkg-config                # [win]
    - m2-base                      # [win]
    - {{ stdlib('c') }}            # [unix]
    - {{ compiler('c') }}          # [unix]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('m2w64_c') }}    # [win]
    - meson
    - ninja

test:
  commands:
    {% set lib_idents = [ "xcvt" ] %}
    {% for lib_ident in lib_idents %}
    - test -f $PREFIX/lib/lib{{ lib_ident }}.dylib  # [osx]
    - test -f $PREFIX/lib/lib{{ lib_ident }}.so  # [linux]
    - if not exist %PREFIX%/Library/lib/lib{{ lib_ident }}.dll.a exit /b 1  # [win]
    {% endfor %}
    - cvt -r -v 1920 1080 60

about:
  home: https://www.x.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'VESA CVT standard timing modeline generation library & utility.'

extra:
  recipe-maintainers:
    - ehfd
